### PR TITLE
Asahi2

### PR DESCRIPTION
**Pull request by slimjimsoftware**
#### Testing the changes
- I tested the changes in this PR: **YES**

### CODE REVIEW

**Comment by dkwo** [comment]
Thanks! I merged it in my branch.

Two minor things:
- as for the printer driver, do you think you can make a PR to void linux directly?
- I'm not sure a new lsp package is acceptable, so for now i split a subpkg (does not take more than 3 min on my laptop): would this be ok? if so, you could make a pr to void for this as well.

**Comment by dkwo** [comment]
ah, another point: can you check that audio still works after these small changes?
also, does the speaker daemon need its own user and home?

**Comment by slimjimsoftware** [comment]
>  as for the printer driver, do you think you can make a PR to void linux directly?

oops - didn't mean to put that one in, was a late night - I was intending to upstream this one, yep will PR direct to void.

>  I'm not sure a new lsp package is acceptable, so for now i split a subpkg (does not take more than 3 min on my laptop): would this be ok? if so, you could make a pr to void for this as well.

sure, that should be fine.

> ah, another point: can you check that audio still works after these small changes?
also, does the speaker daemon need its own user and home?

nope, speakers a broken now - don't have time to check why right now, will do that later

**Comment by dkwo** [comment]
Hmm, sorry for breaking audio.
One thing I changed is that udev rules and conf were previously installed at
```
usr/lib/tmpfiles.d/speakersafetyd.conf/speakersafetyd.tmpfiles
usr/lib/udev/rules.d/95-ssd.rules/95-ssd.rules
```
while now they are at
```
usr/lib/tmpfiles.d/speakersafetyd.conf
usr/lib/udev/rules.d/95-ssd.rules
```
Was that intentional?

**Comment by slimjimsoftware** [comment]
possibly, I just copied what the makefile from the original source was doing - I may well have got that wrong though

**Comment by slimjimsoftware** [comment]
it was the bankstown plugin, the file `libbankstown.so` needed to be renamed `bankstown.so`

**Comment by slimjimsoftware** [comment]
Also found a weird bug that the sound card isn't detected if I boot with my dock (that has it's own soundcard) plugged in, I have to unplug the dock (and possibly the HDMI cable?) until the kernel is booted, don't know if it's m1n1, uboot or the kernel driver causing it at this stage - will probably need to report that to upstream at some point.

**Comment by dkwo** [comment]
thank you.

**Comment by dkwo** [comment]
Feel free to cc me if you report the bug.

**Comment by dkwo** [comment]
for `lsp-plugins`, i did split out stuff and can make a pr to void.
before i do that, can you confirm that with this change audio still works?

**Comment by dkwo** [comment]
(if so, then i'll squash the commits and you can delete your local branch.)

**Comment by slimjimsoftware** [comment]
@dkwo yep, I can confirm with those changes to lsp-plugins audio still works (_and_ the menu entries aren't cluttered with audio plugin entries!). Thanks for all your input, got a fully working void desktop on my mac now and learned a lot in the process - I have to say, I really like runit and xbps-src, it's much simpler than other systems I've packaged stuff for

**Comment by dkwo** [comment]
my pleasure, thanks for helping. hopefully this can be merged in void's repo soon :)

**Pull request merged**
