### PR TITLE
Asahi Rust Compilation Support (for the GPU driver for example)

### PR DESCRIPTION
**Pull request by RoundDuckKira**
This PR will add a few packages (tho it is still early days so it is messy, but it works and does compile the Linux kernel) that will facilitate the ability to compile the Rust components of the Asahi kernel. The reason for this is that some parts of the Asahi code, mainly the GPU, use Rust code, and thus we need a working Rust compiler to compile these bits. That said this is very much WIP (it's a bit messy and wastefully compiles rust-doc, I need to be able to learn to disable that; if not see if I can use the rust/cargo-bootstrap-linux6.6 packages to directly compile the kernel) and I still need another PR that I will soon mention here that will contribute the modified kernel with the Rust-based components compiled.

### CODE REVIEW

**Comment by dkwo** [comment]
Thanks a lot for working on rust.

- do I understand correctly that the bootstrap package is only needed for cross compilation?
- can you put commits in the form like `new package: rust-linux6.6` etc, and rebase?
- since i'm not having a versioned kernel linux6.6, how about use rust-linux, and keep it sync to whatever linux version we build?
- for the kernel, can you add it as say `hostmakedepends+=" rust-linux rust-bindgen-linux rust-src-linux"`
- is cargo really needed? libclang? i.e. does build fail without them?

**Comment by RoundDuckKira** [comment]
@dkwo I'll check and see about these things soon, and how would you put commits in in such a way that I can do it the standard void way, just start fresh and re-add code?

As for the naming, I think asahi would be a better choice but I wonder if we can have naming that reflects the kernel version, like how I did with rust or something like linux-asahi-6.6 or asahi-linux6.6, which matches up with how Void upstream normally does things.

**Comment by dkwo** [comment]
you can use e.g. `git rebase -i HEAD~4` and (s) squash them, and reword along the way.
i think it's simpler to do what void does for the rpi, i.e. only one kernel, tracking asahi version (no virtual pkg etc).
this rust can in principle be used with all recent kernels, not just asahi right?

**Comment by dkwo** [comment]
Since linux 6.11 rust will have a minimum version supported in the kernel, so this should not be needed (it has been working fine already for a while with void's rust).

**Pull request closed without merging**
